// export { WelcomePage } from './landing-page/landing-page'
export { LandingPage } from './landing-page/landing-page'
export { LoadingPage } from './loading-page/loading-page'
export { RegisterPage } from './register-page/register-page'
export { LoginPage } from './login-page/login-page'
export { ForgotPassword } from './forgot-password/forgot-password'
export { VerifyDevice } from './verify-device/verify-device'
export { VerifyAccount } from './verify-account/verify-account'
export { ResetPassword } from './reset-password/reset-password'
export { ContactUs } from './contact-us/contact-us'
export { ReadyToPlay } from './ready-to-play/ready-to-play'